version: '2'

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: 'postgres:12-alpine'
    restart: 'always'
    ports:
      - 5432:5432
    volumes:
    - 'postgres_data:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - app-tier

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami'
    depends_on:
      - postgres

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    networks:
      - app-tier
    volumes:
      - 'kafka_data:/bitnami'
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

volumes:
  postgres_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local